# Generated by Django 5.1.7 on 2025-03-08 14:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('signed_file', models.FileField(blank=True, null=True, upload_to='signed_documents/')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('submitted', 'Submitted')], default='pending', max_length=20)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('signed_date', models.DateTimeField(blank=True, null=True)),
                ('access_token', models.CharField(max_length=16)),
                ('access_expiry', models.DateTimeField()),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('data', models.TextField()),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('signer_email', models.EmailField(max_length=254)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='documents.document')),
            ],
        ),
    ]
