# Generated by Django 5.1.7 on 2025-03-09 07:17

import documents.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_access_token_alter_document_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='signed_file',
            field=models.FileField(blank=True, null=True, storage=documents.storage.PDFStorage(), upload_to='signed_documents/'),
        ),
    ]
